# This vLLM Dockerfile is used to construct image that can build and run vLLM on x86 CPU platform.

FROM registry.access.redhat.com/ubi9/python-311 AS cpu-test-1

USER 0

RUN dnf update -y && \
    dnf install -y cmake gcc gcc-c++ make automake && \
    rpm --import https://www.centos.org/keys/RPM-GPG-KEY-CentOS-Official-SHA256 && \
    dnf install -y https://rpmfind.net/linux/centos-stream/9-stream/AppStream/x86_64/os/Packages/numactl-devel-2.0.19-1.el9.x86_64.rpm && \
    dnf clean all && \
    rm -rf /var/cache/dnf

ENV LD_PRELOAD=""

RUN echo 'ulimit -c 0' >> ~/.bashrc

RUN pip install intel_extension_for_pytorch==2.5.0

WORKDIR /workspace
# 5fbbfe9a4c13094ad72ed3d6b4ef208a7ddc0fd7 - v0.9.0.1
RUN git clone https://github.com/vllm-project/vllm.git && \
    cd vllm && \
    git checkout 5fbbfe9a4c13094ad72ed3d6b4ef208a7ddc0fd7

ARG PIP_EXTRA_INDEX_URL="https://download.pytorch.org/whl/cpu"
ENV PIP_EXTRA_INDEX_URL=${PIP_EXTRA_INDEX_URL}

WORKDIR /workspace/vllm
RUN --mount=type=cache,target=/root/.cache/pip \
    pip install --upgrade pip && \
    pip install -r requirements/build.txt
WORKDIR /workspace

FROM cpu-test-1 AS build

WORKDIR /workspace/vllm

RUN --mount=type=cache,target=/root/.cache/pip \
    pip install -v -r requirements/cpu.txt

COPY . .
ARG GIT_REPO_CHECK=0
RUN if [ "$GIT_REPO_CHECK" != 0 ]; then bash tools/check_repo.sh ; fi

# Support for building with non-AVX512 vLLM
ARG VLLM_CPU_DISABLE_AVX512
ENV VLLM_CPU_DISABLE_AVX512=${VLLM_CPU_DISABLE_AVX512}

RUN --mount=type=cache,target=/root/.cache/pip \
    VLLM_TARGET_DEVICE=cpu python3 setup.py bdist_wheel && \
    pip install dist/*.whl && \
    rm -rf dist

WORKDIR /workspace/

RUN ln -s /workspace/vllm/tests && ln -s /workspace/vllm/examples && ln -s /workspace/vllm/benchmarks

# Install development dependencies (for testing)
RUN --mount=type=cache,target=/root/.cache/pip \
    pip install -e tests/vllm_test_utils

USER 1001

ENTRYPOINT ["vllm", "serve"]
# ENTRYPOINT ["python3", "-m", "vllm.entrypoints.openai.api_server"]
